# https://pre-commit.com/#new-hooks
# https://engineeringfordatascience.com/posts/pre_commit_yaml/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.1
  hooks:
    - id: gitleaks
