name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      #- 'docs/**.md'
      #- 'docs/images/**'
      - docs/book/AWS/AWS_Solution_Architect.md

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs/book/AWS/AWS_Solution_Architect.md
          output_dir: docs/book/AWS/
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
