name: linksCheck
# runs every monday at 9 am
on:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-links:
    uses: carlosrodlop/gha-lib/.github/workflows/mdLinkChecker.shared.yml@main
    with:
      file-path: "**/*.md"
